"""password column

Revision ID: 298894d0f07c
Revises: 44a7dea7411b
Create Date: 2020-10-25 03:04:35.847179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298894d0f07c'
down_revision = '44a7dea7411b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
